#!/bin/bash
BIN_DIR="bin"
JAVAC="/usr/bin/javac"
JAR="/usr/bin/jar"

if [ ! -d "$BIN_DIR" ]; then
    mkdir $BIN_DIR
fi
$JAVAC -d $BIN_DIR/ src/business/* src/entities/* src/structures/*
cd $BIN_DIR/
$JAR cfe DataStruct.jar business.Main business/* entities/* structures/*
cd ../
mv $BIN_DIR/DataStruct.jar .
