#!/bin/bash
if [ ! -d "bin" ]; then
    mkdir bin
fi
javac -d bin/ src/business/* src/entities/* src/structures/*
cd bin/
jar cfe DataStruct.jar business.Main business/* entities/* structures/*
cd ../
mv bin/DataStruct.jar .
